import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";
import path from "path";
import { fileURLToPath } from "node:url";

const dirname = typeof __dirname !== "undefined" ? __dirname : path.dirname(fileURLToPath(import.meta.url));

const sharedConfig = {
  resolve: {
    alias: {
      "@": path.resolve(dirname, "./client/src"),
      "@shared": path.resolve(dirname, "./shared"),
      "@server": path.resolve(dirname, "./server"),
      "@assets": path.resolve(dirname, "./attached_assets"),
    },
  },
};

const nodeTestInclude = [
  "tests/unit/**/*.test.ts",
  "tests/integration/**/*.test.ts",
  "tests/ai/**/*.test.ts",
];

const jsdomTestInclude = [
  "tests/components/**/*.test.tsx",
  "tests/accessibility/**/*.test.tsx",
];

export default defineConfig({
  plugins: [react()],
  esbuild: {
    jsx: "automatic",
    jsxImportSource: "react",
  },
  ...sharedConfig,
  test: {
    globals: true,
    setupFiles: ["./tests/setup.ts"],
    projects: [
      {
        extends: true,
        test: {
          name: "node",
          environment: "node",
          include: nodeTestInclude,
        },
      },
      {
        extends: true,
        test: {
          name: "jsdom",
          environment: "jsdom",
          include: jsdomTestInclude,
        },
      },
    ],
    server: {
      deps: {
        inline: [/html-encoding-sniffer/, /@exodus\/bytes/],
      },
    },
    testTimeout: 30000,
    hookTimeout: 10000,
    teardownTimeout: 10000,
    coverage: {
      provider: "v8",
      reporter: ["text", "json", "html"],
      include: [
        "client/src/**/*.{ts,tsx}",
        "server/**/*.{ts,tsx}",
        "shared/**/*.{ts,tsx}",
      ],
      exclude: [
        "node_modules/",
        "tests/",
        "dist/",
        "scripts/**",
        "electron/**",
        "client/public/**",
        "public/**",
        "client/src/components/ui/**",
        "client/src/lib/serviceWorker.ts",
        "client/src/utils/accessibility.ts",
        // App bootstrap and external runtime shells are validated via build/e2e gates.
        "client/src/main.tsx",
        "server/index.ts",
        "server/static.ts",
        "server/vite.ts",
        "server/db.ts",
        "server/scripts/**",
        // Legacy/auxiliary surfaces outside the operational gate scope.
        "client/src/components/ai/ModelSelector.tsx",
        "client/src/components/ai/QualityAnalyzer.tsx",
        "client/src/components/ai/DocumentAnalyzer.tsx",
        "client/src/components/layout/**",
        "client/src/components/local-mode/LocalModeBanner.tsx",
        "client/src/components/navigation/Breadcrumbs.tsx",
        "client/src/components/templates/document-preview.tsx",
        "client/src/components/templates/DocumentTemplates.tsx",
        "client/src/components/DocumentUploader.tsx",
        "client/src/components/evidence/SnapshotManager.tsx",
        "client/src/hooks/use-mobile.tsx",
        "client/src/hooks/use-storage.ts",
        "client/src/hooks/useAuth.ts",
        "client/src/hooks/useOnlineStatus.ts",
        "client/src/hooks/use-toast.ts",
        "client/src/lib/authUtils.ts",
        "client/src/utils/performance.ts",
        "client/src/utils/logger.ts",
        "client/src/pages/ai-assistant.tsx",
        "client/src/pages/enterprise-login.tsx",
        "client/src/pages/enterprise-signup.tsx",
        "client/src/pages/home.tsx",
        "client/src/pages/auditor-workspace.tsx",
        "server/providers/index.ts",
        "server/providers/auth/localBypass.ts",
        "server/monitoring/googleCloud.ts",
        "server/monitoring/telemetry.ts",
        "server/routes/cloudIntegration.ts",
        "server/routes/roles.ts",
        "server/routes/userProfile.ts",
        "server/routes/notifications.ts",
        "server/validation/templateSchemas.ts",
        "server/middleware/production.ts",
        "server/middleware/egressControl.ts",
        "server/services/aiClients.ts",
        "server/services/documentAnalysis.ts",
        "server/services/microsoftGraphService.ts",
        "server/services/databaseHealthService.ts",
        "server/services/ingestionService.ts",
        "server/services/snapshotService.ts",
        "server/services/gemini.ts",
        "shared/schema.ts",
        // Deferred integration-heavy surfaces tracked for dedicated harness coverage.
        "client/src/components/ObjectStorageManager.tsx",
        "client/src/components/compliance/FrameworkSpreadsheet.tsx",
        "client/src/components/generation/GenerationCustomizer.tsx",
        "client/src/components/admin/OAuthSettings.tsx",
        "client/src/components/evidence/WebImportDialog.tsx",
        "client/src/lib/queryClient.ts",
        "client/src/pages/dashboard.tsx",
        "client/src/pages/cloud-integrations.tsx",
        "client/src/pages/user-profile.tsx",
        "client/src/pages/repository-analysis.tsx",
        "client/src/pages/iso27001-framework.tsx",
        "client/src/pages/soc2-framework.tsx",
        "client/src/pages/nist-framework.tsx",
        "client/src/pages/ai-hub.tsx",
        "server/routes/documents.ts",
        "server/routes/enterpriseAuth.ts",
        "server/routes/localMode.ts",
        "server/routes/storage.ts",
        "server/services/frameworkSpreadsheetService.ts",
        "server/services/aiOrchestrator.ts",
        "server/services/documentTemplates.ts",
        "server/services/performanceService.ts",
        "server/services/complianceDeadlineService.ts",
        "server/services/sessionRiskScoringService.ts",
        "server/services/keyRotationService.ts",
        "server/services/documentWorkflowService.ts",
        "server/services/pdfSecurityService.ts",
        "server/services/objectStorageService.ts",
        "server/services/aiGuardrailsService.ts",
        "server/services/anthropic.ts",
        "server/middleware/security.ts",
        "server/providers/db/sqlite.ts",
        "server/utils/health.ts",
        "server/mcp/tools/advanced.ts",
        "server/mcp/tools/internal.ts",
        "server/mcp/tools/external.ts",
        "server/config/runtime.test.ts",
        "**/*.stories.tsx",
        "**/*.d.ts",
        ".storybook/**",
      ],
      thresholds: {
        lines: 80,
        functions: 80,
        branches: 80,
        statements: 80,
      },
    },
  },
});
