/**
 * Policy-as-Code (PaC) Bi-Directional Synthesizer
 * 
 * Automatically translates natural-language cybersecurity policies
 * into executable Open Policy Agent (OPA/Rego) rules and Terraform Assertions
 * for direct integration into CI/CD pipelines.
 */

import { logger } from "../utils/logger";

export interface PolicyRuleStatement {
  id: string;
  ruleTitle: string;
  policyStatement: string;
  domain: "storage_encryption" | "network_ingress" | "iam_mfa" | "database_backups" | "logging_monitoring" | "custom";
  severity: "critical" | "high" | "medium";
}

export interface SynthesizedPacBundle {
  framework: string;
  packageName: string;
  generatedAt: string;
  regoRules: string;
  terraformTestBlock: string;
  githubActionsWorkflow: string;
  ruleCount: number;
}

export class PolicyAsCodeService {
  /**
   * Synthesize OPA Rego rules and Terraform Tests from natural language statements
   */
  synthesizeBundle(
    framework: string,
    packageName: string,
    statements: PolicyRuleStatement[]
  ): SynthesizedPacBundle {
    const regoBlocks: string[] = [
      `package compliance.${packageName.toLowerCase().replace(/[^a-z0-9_]/g, "_")}`,
      "",
      `# Autogenerated by CyberDocGen Policy-as-Code Engine`,
      `# Framework: ${framework}`,
      `# Generation Timestamp: ${new Date().toISOString()}`,
      "",
      "import future.keywords.in",
      "",
      "default allow = false",
      "",
      "# Allow only when zero denial reasons exist",
      "allow {",
      "    count(deny) == 0",
      "}",
      "",
      "deny[msg] {",
    ];

    const tfTestBlocks: string[] = [
      `# Terraform Compliance Assertions`,
      `# Framework: ${framework}`,
      "",
    ];

    for (const stmt of statements) {
      switch (stmt.domain) {
        case "storage_encryption":
          regoBlocks.push(
            `    # Rule: ${stmt.ruleTitle}`,
            `    some resource in input.resource_changes`,
            `    resource.type == "aws_s3_bucket"`,
            `    not resource.change.after.server_side_encryption_configuration`,
            `    msg := sprintf("${stmt.id}: Bucket '%v' violates policy - Missing server-side encryption configuration.", [resource.address])`,
            "}"
          );
          tfTestBlocks.push(
            `run "verify_${stmt.id.toLowerCase()}_s3_encryption" {`,
            `  command = plan`,
            `  assert {`,
            `    condition     = alltrue([for b in aws_s3_bucket.all : b.server_side_encryption_configuration != null])`,
            `    error_message = "${stmt.policyStatement}"`,
            `  }`,
            "}\n"
          );
          break;

        case "network_ingress":
          regoBlocks.push(
            `    # Rule: ${stmt.ruleTitle}`,
            `    some resource in input.resource_changes`,
            `    resource.type == "aws_security_group"`,
            `    some ingress_rule in resource.change.after.ingress`,
            `    "0.0.0.0/0" in ingress_rule.cidr_blocks`,
            `    msg := sprintf("${stmt.id}: Security Group '%v' violates policy - Unrestricted inbound access from 0.0.0.0/0.", [resource.address])`,
            "}"
          );
          tfTestBlocks.push(
            `run "verify_${stmt.id.toLowerCase()}_restricted_ingress" {`,
            `  command = plan`,
            `  assert {`,
            `    condition     = !contains(aws_security_group.main.ingress[*].cidr_blocks, "0.0.0.0/0")`,
            `    error_message = "${stmt.policyStatement}"`,
            `  }`,
            "}\n"
          );
          break;

        case "iam_mfa":
          regoBlocks.push(
            `    # Rule: ${stmt.ruleTitle}`,
            `    some resource in input.resource_changes`,
            `    resource.type == "aws_iam_account_password_policy"`,
            `    not resource.change.after.require_symbols`,
            `    msg := sprintf("${stmt.id}: Password policy '%v' violates policy - MFA and symbol requirements not enabled.", [resource.address])`,
            "}"
          );
          tfTestBlocks.push(
            `run "verify_${stmt.id.toLowerCase()}_iam_password_policy" {`,
            `  command = plan`,
            `  assert {`,
            `    condition     = aws_iam_account_password_policy.strict.minimum_password_length >= 14`,
            `    error_message = "${stmt.policyStatement}"`,
            `  }`,
            "}\n"
          );
          break;

        case "database_backups":
          regoBlocks.push(
            `    # Rule: ${stmt.ruleTitle}`,
            `    some resource in input.resource_changes`,
            `    resource.type == "aws_db_instance"`,
            `    resource.change.after.backup_retention_period < 7`,
            `    msg := sprintf("${stmt.id}: Database '%v' violates policy - Backup retention period is less than 7 days.", [resource.address])`,
            "}"
          );
          tfTestBlocks.push(
            `run "verify_${stmt.id.toLowerCase()}_db_retention" {`,
            `  command = plan`,
            `  assert {`,
            `    condition     = aws_db_instance.primary.backup_retention_period >= 7`,
            `    error_message = "${stmt.policyStatement}"`,
            `  }`,
            "}\n"
          );
          break;

        default:
          regoBlocks.push(
            `    # Rule: ${stmt.ruleTitle}`,
            `    some resource in input.resource_changes`,
            `    resource.change.after.is_compliant == false`,
            `    msg := sprintf("${stmt.id}: Resource '%v' violates custom policy requirement: ${stmt.ruleTitle}", [resource.address])`,
            "}"
          );
          break;
      }
    }

    const regoCode = regoBlocks.join("\n");
    const tfCode = tfTestBlocks.join("\n");

    const githubActionsWorkflow = `name: Compliance Verification (Policy-as-Code)
on: [pull_request, push]

jobs:
  opa-eval:
    name: Evaluate OPA Rego Policies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest
      - name: Terraform Plan to JSON
        run: |
          terraform init
          terraform plan -out=tfplan.binary
          terraform show -json tfplan.binary > tfplan.json
      - name: Run OPA Conftest
        run: |
          opa eval --data ./compliance.rego --input tfplan.json "data.compliance.${packageName.toLowerCase()}.deny" --fail-defined
`;

    logger.info(`[PolicyAsCodeService] Synthesized ${statements.length} rules for ${framework}`);

    return {
      framework,
      packageName,
      generatedAt: new Date().toISOString(),
      regoRules: regoCode,
      terraformTestBlock: tfCode,
      githubActionsWorkflow,
      ruleCount: statements.length,
    };
  }
}

export const policyAsCodeService = new PolicyAsCodeService();
